### PR TITLE
Black and white filter feature

### PR DESCRIPTION
**Pull request by sbouchard09**
- added an icon to enable/disable the feature
- added ability to capture an image in black and white
- added the ability to save a black and white image to the phone
- also works when recording video

### CODE REVIEW

**Review by Keeran10 — CHANGES_REQUESTED** [review]
Please provide some comments on your functions for ease of learning and traceability. Thanks !

**Comment by sbouchard09** [comment]
> 
> 
> Please provide some comments on your functions for ease of learning and traceability. Thanks !

done!

**Review by Keeran10 — APPROVED** [review]

**Comment by soenAnt** [comment]
Good job, the code is very readable and clear. I notice that the feature doesn't work for the 'selfie' camera, mind adding that in?

**Comment by sbouchard09** [comment]
> 
> 
> Good job, the code is very readable and clear. I notice that the feature doesn't work for the 'selfie' camera, mind adding that in?

done, but now there's a weird bug with the rear facing camera.

**Pull request merged**
